"""
Overview Page
Instant understanding of the system
"""

import streamlit as st
import pandas as pd
from pathlib import Path


def load_data():
    """Load summary data"""
    data = {}
    
    # HPC summary
    hpc_path = Path('../data/hpc_results_summary.csv')
    if hpc_path.exists():
        data['hpc'] = pd.read_csv(hpc_path)
    
    # BI insights
    bi_path = Path('../data/bi_insights_summary.csv')
    if bi_path.exists():
        data['bi'] = pd.read_csv(bi_path)
    
    # Thread scaling
    thread_path = Path('../data/hpc_thread_scaling.csv')
    if thread_path.exists():
        data['threads'] = pd.read_csv(thread_path)
    
    return data


def render():
    """Render overview page"""
    
    # Title
    st.title("🚀 HPC + BI Retail Analytics System")
    st.markdown("**Understanding customer behavior through fast computation and meaningful insights**")
    st.markdown("---")
    
    # Load data
    data = load_data()
    
    # Problem Statement
    st.header("📋 The Challenge")
    col1, col2 = st.columns([2, 1])
    
    with col1:
        st.markdown("""
        **Large Dataset Analysis**
        - 📦 **~400,000 transactions** to process
        - 👥 **4,338 customers** to understand
        - ⏱️ **Fast computation** required
        - 💡 **Meaningful insights** needed
        """)
    
    with col2:
        st.info("""
        **Goal:**
        Analyze retail data quickly and accurately to understand customer behavior and drive business decisions.
        """)
    
    st.markdown("---")
    
    # Our Approach
    st.header("🎯 Our Approach: Two Systems Working Together")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("""
        ### ⚡ HPC Engine (High-Performance Computing)
        **Technology:** C++ with OpenMP (Parallel Processing)
        
        **Role:**
        - ✅ Fast computation on large datasets
        - ✅ Parallel processing (multiple threads)
        - ✅ Handles heavy calculations
        
        **Output:**
        - Revenue metrics
        - RFM analysis
        - Statistical computations
        """)
    
    with col2:
        st.markdown("""
        ### 💼 BI Layer (Business Intelligence)
        **Technology:** Python with pandas & scikit-learn
        
        **Role:**
        - ✅ Data cleaning & preparation
        - ✅ Customer segmentation
        - ✅ Business insights generation
        
        **Output:**
        - Customer segments
        - Revenue patterns
        - Actionable recommendations
        """)
    
    st.markdown("---")
    
    # Key Metrics
    st.header("📊 System Performance at a Glance")
    
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        if 'hpc' in data:
            revenue = data['hpc'][data['hpc']['metric'] == 'total_revenue']['value'].values
            if len(revenue) > 0:
                st.metric(
                    "💰 Total Revenue",
                    f"${revenue[0]:,.0f}",
                    help="Total revenue processed by both HPC and BI"
                )
    
    with col2:
        if 'bi' in data:
            customers = data['bi'][data['bi']['dimension'] == 'total']['value'].values
            if len(customers) > 0:
                st.metric(
                    "👥 Total Customers",
                    f"{int(customers[0]):,}",
                    help="Unique customers analyzed"
                )
    
    with col3:
        if 'threads' in data:
            max_speedup = data['threads']['speedup'].max()
            st.metric(
                "⚡ HPC Speedup",
                f"{max_speedup:.2f}x",
                help="Performance improvement with parallel processing"
            )
    
    with col4:
        if 'bi' in data:
            total_insights = len(data['bi'])
            st.metric(
                "💡 Total Insights",
                f"{total_insights}",
                help="Business insights generated by BI layer"
            )
    
    st.markdown("---")
    
    # System Architecture
    st.header("🏗️ How It Works")
    
    st.markdown("""
    ```
    📁 Raw Data (Online Retail Dataset)
           │
           ├─────────────────┬─────────────────┐
           │                 │                 │
           ▼                 ▼                 │
    ⚡ HPC Engine      💼 BI Layer            │
    (C++ OpenMP)      (Python)               │
           │                 │                 │
           │                 │                 │
           ▼                 ▼                 │
    📊 HPC Results    📊 BI Results           │
           │                 │                 │
           └────────┬────────┘                 │
                    ▼                          │
            🔗 Validation                      │
         (Compare Results)                     │
                    │                          │
                    ▼                          │
            ✅ Verified Results                │
                    │                          │
                    └──────────────────────────┘
                    │
                    ▼
            📊 Dashboard (You are here!)
    ```
    """)
    
    st.markdown("---")
    
    # Key Message
    st.header("🎯 The Complete Picture")
    
    col1, col2, col3 = st.columns(3)
    
    with col1:
        st.markdown("""
        <div class="insight-box">
        <h4>⚡ HPC Ensures Speed</h4>
        <p>Parallel processing reduces computation time, enabling real-time analytics on large datasets.</p>
        </div>
        """, unsafe_allow_html=True)
    
    with col2:
        st.markdown("""
        <div class="insight-box">
        <h4>💼 BI Ensures Insights</h4>
        <p>Business intelligence transforms raw data into actionable recommendations for decision-making.</p>
        </div>
        """, unsafe_allow_html=True)
    
    with col3:
        st.markdown("""
        <div class="insight-box">
        <h4>🔗 Validation Ensures Correctness</h4>
        <p>Cross-validation between HPC and BI confirms accuracy and builds confidence in results.</p>
        </div>
        """, unsafe_allow_html=True)
    
    st.markdown("---")
    
    # Navigation hint
    st.info("""
    👉 **Next Steps:**
    - Explore **HPC Engine** to see how parallel processing works
    - Explore **BI Layer** to see business insights
    - Check **System Integration** to see how HPC and BI connect
    - View **Results & Impact** for final summary
    """)
